### ISSUE TITLE
Mensaje de error en dnmye_colores no muestra opciones

### ISSUE THREAD

**Issue by jpruiznicolini** [d4t4tur/comunicacion#1]
![imagen](https://user-images.githubusercontent.com/96128473/161066766-f1fa1891-d6d2-4f01-94b4-c915e13f1bd4.png)

**Comment by pablotis** [comment]
Resuelto. Cierro.
![imagen](https://user-images.githubusercontent.com/30708601/168387916-2864ad58-1dde-4fb3-a825-bb999c128f33.png)
