### ISSUE TITLE
Revisar colores y códigos hex en `dnmye_colores()`

### ISSUE THREAD

**Issue by eliansoutu** [d4t4tur/comunicacion#10]
A riesgo de exponer mi daltonismo, algunos códigos hex parecieran no coincidir con los colores:

```
comunicacion::dnmye_colores("rojo")
#EE3D8F
```
![image](https://user-images.githubusercontent.com/62449092/168173027-7e5ec1c7-a7a3-4681-acc3-fea8d0c55e4c.png)

```
comunicacion::dnmye_colores("violeta")
#9283BE
```
![image](https://user-images.githubusercontent.com/62449092/168172967-34004886-2d07-4758-9439-d92e6cf47f6a.png)

```
comunicacion::dnmye_colores("verde oscuro")
#50B8B1
```
![image](https://user-images.githubusercontent.com/62449092/168172897-ca17f739-a701-455f-b016-ee3a28e34a63.png)

```
comunicacion::dnmye_colores("gris oscuro")
#50535C
```
![image](https://user-images.githubusercontent.com/62449092/168172614-a34dc777-1758-4598-b287-bf93f502eab3.png)

**Comment by pablotis** [comment]
Absolutamente! 

Busqué fuente de nombres para código hex, encontré la siguiente: https://coolors.co/e7e7e7

En base a ello, armé la siguiente propuesta, con el objetivo de perder cierta precisión en el nombre para no perder intuición en el uso:

```
colores <- c(
  `rosa`         = "#EE3D8F",
  `naranja`      = "#F7941E",
  `amarillo`     = "#FFD100",
  `pera`         = "#D7DF23",
  `azul verde`   = "#50B8B1",
  `purpura`      = "#9283BE",
  `cian`         = "#37BBED",
  `gris oscuro`  = "#50535C",
  `gris plata`   = "#AAAAAA",
  `plateado`     = "#E7E7E7")
```

**Comment by eliansoutu** [comment]
Esos pasarían a ser los colores que tome la función en adelante? Pregunto porque en algunos proyectos estoy usando las denominaciones previas, como el violeta o el verde claro.

**Comment by pablotis** [comment]
Si, deberíamos acordar uno y ya le damos cierre, lo que haría que revisemos aquellos scripts con los nombres anteriores.
¿Esta versión cómo la ves / ven? cc @TuQmano @jurricariet @jgjuara

**Comment by eliansoutu** [comment]
Lo veo bien pero si los nombres están pensados para ajustarse a la paleta oficial podemos mantenerlos, nos ahorramos de paso de tener que modificar los scripts con los nombres originales. Pensé que había un error en la asignación del código hex.

**Comment by pablotis** [comment]
el error fue de mi parte en la asignación de nombre! Para mí está bien darle un ajuste. Por ejemplo, `"rojo"` no pega ni de cerca, claramente hay que cambiarlo. Yo diría que duela pero que valga la pena.

**Comment by pablotis** [comment]
Hechos los cambios. Versión final (nadie comentó que no había diferencia entre _gris plata_ y _plateado_ XD):

```
colores <- c(
  `rosa`         = "#EE3D8F",
  `naranja`      = "#F7941E",
  `amarillo`     = "#FFD100",
  `pera`         = "#D7DF23",
  `azul verde`   = "#50B8B1",
  `purpura`      = "#9283BE",
  `cian`         = "#37BBED",
  `gris oscuro`  = "#50535C",
  `gris medio`   = "#AAAAAA",
  `gris claro`   = "#E7E7E7")
```
