### ISSUE TITLE
Template Xaringan

### ISSUE THREAD

**Issue by TuQmano** [d4t4tur/comunicacion#2]
Armar _theme_  institucional para presentaciones @pablotis

**Comment by jpruiznicolini** [comment]
Ejemplo para edición de `title_slide` https://github.com/keithmcnulty/causal_inference_intro/blob/main/style.css#L120

**Comment by jpruiznicolini** [comment]
`{xaringanthemer}` para generar `.css` de tema Xaringan https://pkg.garrickadenbuie.com/xaringanthemer/

**Comment by jpruiznicolini** [comment]
Boceto armado en este repo https://github.com/dnme-minturdep/dnmye_xaringan_template

Integrar en una función de `{comunicacion}` @pablotis
