### ISSUE TITLE
Función `gt_theme_dnmye()`

### ISSUE THREAD

**Issue by jurricariet** [d4t4tur/comunicacion#27]
Tenemos 2 sugerencias para la función:

- **Alineación columnas:** actualmente centra a partir de la segunda columna. Se podría especificar que la primera la alinee a la izquierda
- **Variables coloreadas:** sacar el color condicional para las columnas relativas a proporciones, ahí no hace falta

**Comment by eliansoutu** [comment]
Hecho #36 !
