### ISSUE TITLE
Agregar función para crear template por consola a lo `comunicacion::crear_informe()`

### ISSUE THREAD

**Issue by pablotis** [d4t4tur/comunicacion#3]
Hoy la función armar template vía panel de control al crear un Rmarkdown por File --> New file --> Rmarkdown --> From Template --> comunicacion

**Comment by TuQmano** [comment]
Hecho en https://github.com/dnme-minturdep/comunicacion/commit/a7e38f2384002e6bae88da210ac85484c9dd388c
